# https://golangci-lint.run/usage/configuration/#config-file
version: "2"

linters:
  default: standard
  enable:
    - govet  # Detects suspicious constructs (e.g., printf format issues, unused variables).
    - staticcheck  # Performs advanced static analysis for potential bugs and inefficiencies.
    - ineffassign  # Detects redundant assignments that have no effect.
    - gosimple  # Suggests simpler alternatives to complex Go constructs.
    # - revive  # Provides style and best practice suggestions.
    - gosec  # Checks for common security issues in Go code.
    - misspell  # Finds and corrects spelling mistakes in comments and strings.
    - gofmt  # Ensures code follows Go formatting standards.
    - unconvert # Detect unnecessary type conversions.
    - bodyclose # Detects HTTP response bodies that are not closed.
    - testpackage # Checks for test files that do not belong to a package named `*_test`.
    - goconst # Detects repeated string literals and suggests using constants instead.
    - unparam # Detect unused function parameters.
  settings:
    gocyclo:
      min-complexity: 15  # Warn if a function has a complexity score of 15 or higher.
    errcheck:
      check-type-assertions: false  # Ignore type assertion errors.
      check-blank: false  # Ignore blank identifier errors.
    misspell:
      locale: US  # Use US English for spell checking.
  exclusions:
    paths:
      - ".*_test\\.go"
      - ".*_gen\\.go"
      - ".*mock.*\\.go"
      - "internal/.*/mocks/.*"
      - "internal/infra/db/model_gen/.*"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true  # Apply simplifications, such as removing redundant conversions.
  exclusions:
    # Log a warning if an exclusion path is unused.
    warn-unused: false
    # Mode of the generated files analysis.
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    generated: strict
    # Which file paths to exclude.
    paths:
      - ".*_test\\.go"
      - ".*_gen\\.go"
      - ".*mock.*\\.go"
      - "internal/.*/mocks/.*"
      - "internal/infra/db/model_gen/.*"