//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Concerts struct {
	ID        uuid.UUID `sql:"primary_key" db:"concerts.id"`
	Name      string    `db:"concerts.name"`
	Date      time.Time `db:"concerts.date"`
	Venue     string    `db:"concerts.venue"`
	CreatedAt time.Time `db:"concerts.created_at"`
	UpdatedAt time.Time `db:"concerts.updated_at"`
}
