//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"time"
)

type Payments struct {
	ID            uuid.UUID        `sql:"primary_key" db:"payments.id"`
	ReservationID uuid.UUID        `db:"payments.reservation_id"`
	Status        string           `db:"payments.status"`
	Amount        *decimal.Decimal `db:"payments.amount"`
	PaidAt        *time.Time       `db:"payments.paid_at"`
	PaymentMethod *string          `db:"payments.payment_method"`
	CreatedAt     time.Time        `db:"payments.created_at"`
	UpdatedAt     time.Time        `db:"payments.updated_at"`
}
