//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Reservations struct {
	ID         uuid.UUID `sql:"primary_key" db:"reservations.id"`
	SeatID     uuid.UUID `db:"reservations.seat_id"`
	SessionID  string    `db:"reservations.session_id"`
	Status     string    `db:"reservations.status"`
	ReservedAt time.Time `db:"reservations.reserved_at"`
	ExpiresAt  time.Time `db:"reservations.expires_at"`
	CreatedAt  time.Time `db:"reservations.created_at"`
	UpdatedAt  time.Time `db:"reservations.updated_at"`
}
