//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Seats struct {
	ID                uuid.UUID  `sql:"primary_key" db:"seats.id"`
	ZoneID            uuid.UUID  `db:"seats.zone_id"`
	SeatNumber        string     `db:"seats.seat_number"`
	Status            string     `db:"seats.status"`
	LockedUntil       *time.Time `db:"seats.locked_until"`
	LockedBySessionID *string    `db:"seats.locked_by_session_id"`
	CreatedAt         time.Time  `db:"seats.created_at"`
	UpdatedAt         time.Time  `db:"seats.updated_at"`
}
