//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Zones struct {
	ID          uuid.UUID `sql:"primary_key" db:"zones.id"`
	ConcertID   uuid.UUID `db:"zones.concert_id"`
	Name        string    `db:"zones.name"`
	Description *string   `db:"zones.description"`
	CreatedAt   time.Time `db:"zones.created_at"`
	UpdatedAt   time.Time `db:"zones.updated_at"`
}
