// Code generated by MockGen. DO NOT EDIT.
// Source: ./health_check_repository.go

// Package cache_mocks is a generated GoMock package.
package cache_mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHealthCheckRepository is a mock of HealthCheckRepository interface.
type MockHealthCheckRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckRepositoryMockRecorder
}

// MockHealthCheckRepositoryMockRecorder is the mock recorder for MockHealthCheckRepository.
type MockHealthCheckRepositoryMockRecorder struct {
	mock *MockHealthCheckRepository
}

// NewMockHealthCheckRepository creates a new mock instance.
func NewMockHealthCheckRepository(ctrl *gomock.Controller) *MockHealthCheckRepository {
	mock := &MockHealthCheckRepository{ctrl: ctrl}
	mock.recorder = &MockHealthCheckRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckRepository) EXPECT() *MockHealthCheckRepositoryMockRecorder {
	return m.recorder
}

// CheckRedisReadiness mocks base method.
func (m *MockHealthCheckRepository) CheckRedisReadiness(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRedisReadiness", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRedisReadiness indicates an expected call of CheckRedisReadiness.
func (mr *MockHealthCheckRepositoryMockRecorder) CheckRedisReadiness(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRedisReadiness", reflect.TypeOf((*MockHealthCheckRepository)(nil).CheckRedisReadiness), ctx)
}
