// Code generated by MockGen. DO NOT EDIT.
// Source: ./seat_lock_repository.go

// Package cache_mocks is a generated GoMock package.
package cache_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatLockerRepository is a mock of SeatLockerRepository interface.
type MockSeatLockerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatLockerRepositoryMockRecorder
}

// MockSeatLockerRepositoryMockRecorder is the mock recorder for MockSeatLockerRepository.
type MockSeatLockerRepositoryMockRecorder struct {
	mock *MockSeatLockerRepository
}

// NewMockSeatLockerRepository creates a new mock instance.
func NewMockSeatLockerRepository(ctrl *gomock.Controller) *MockSeatLockerRepository {
	mock := &MockSeatLockerRepository{ctrl: ctrl}
	mock.recorder = &MockSeatLockerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatLockerRepository) EXPECT() *MockSeatLockerRepositoryMockRecorder {
	return m.recorder
}

// LockSeat mocks base method.
func (m *MockSeatLockerRepository) LockSeat(ctx context.Context, concertID, zoneID, seatID uuid.UUID, token string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSeat", ctx, concertID, zoneID, seatID, token, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockSeat indicates an expected call of LockSeat.
func (mr *MockSeatLockerRepositoryMockRecorder) LockSeat(ctx, concertID, zoneID, seatID, token, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSeat", reflect.TypeOf((*MockSeatLockerRepository)(nil).LockSeat), ctx, concertID, zoneID, seatID, token, ttl)
}

// UnlockSeat mocks base method.
func (m *MockSeatLockerRepository) UnlockSeat(ctx context.Context, concertID, zoneID, seatID uuid.UUID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockSeat", ctx, concertID, zoneID, seatID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockSeat indicates an expected call of UnlockSeat.
func (mr *MockSeatLockerRepositoryMockRecorder) UnlockSeat(ctx, concertID, zoneID, seatID, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockSeat", reflect.TypeOf((*MockSeatLockerRepository)(nil).UnlockSeat), ctx, concertID, zoneID, seatID, token)
}
