//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Payments = newPaymentsTable("public", "payments", "")

type paymentsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	ReservationID postgres.ColumnString
	Status        postgres.ColumnString
	Amount        postgres.ColumnFloat
	PaidAt        postgres.ColumnTimestampz
	PaymentMethod postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PaymentsTable struct {
	paymentsTable

	EXCLUDED paymentsTable
}

// AS creates new PaymentsTable with assigned alias
func (a PaymentsTable) AS(alias string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PaymentsTable with assigned schema name
func (a PaymentsTable) FromSchema(schemaName string) *PaymentsTable {
	return newPaymentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PaymentsTable with assigned table prefix
func (a PaymentsTable) WithPrefix(prefix string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PaymentsTable with assigned table suffix
func (a PaymentsTable) WithSuffix(suffix string) *PaymentsTable {
	return newPaymentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPaymentsTable(schemaName, tableName, alias string) *PaymentsTable {
	return &PaymentsTable{
		paymentsTable: newPaymentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newPaymentsTableImpl("", "excluded", ""),
	}
}

func newPaymentsTableImpl(schemaName, tableName, alias string) paymentsTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		ReservationIDColumn = postgres.StringColumn("reservation_id")
		StatusColumn        = postgres.StringColumn("status")
		AmountColumn        = postgres.FloatColumn("amount")
		PaidAtColumn        = postgres.TimestampzColumn("paid_at")
		PaymentMethodColumn = postgres.StringColumn("payment_method")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, ReservationIDColumn, StatusColumn, AmountColumn, PaidAtColumn, PaymentMethodColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{ReservationIDColumn, StatusColumn, AmountColumn, PaidAtColumn, PaymentMethodColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return paymentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		ReservationID: ReservationIDColumn,
		Status:        StatusColumn,
		Amount:        AmountColumn,
		PaidAt:        PaidAtColumn,
		PaymentMethod: PaymentMethodColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
