//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Concerts = Concerts.FromSchema(schema)
	Payments = Payments.FromSchema(schema)
	Reservations = Reservations.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	Seats = Seats.FromSchema(schema)
	Zones = Zones.FromSchema(schema)
}
